feat: add clip_hg executor
jina-ai/clip-as-service pull request #740
Opened 2022-06-01 04:41 UTC by ZiniuYu

2022-06-01 04:49 UTC, numb3r3 requested changes
- add `rank()` endpoint
- add unittest
- add dependency of `transformers` into `setup.py`

2022-06-01 04:49 UTC, numb3r3 commented on server/clip_server/executors/clip_hg.py
> +        )
Polish this block by following implementations in other backends.

2022-06-01 04:49 UTC, numb3r3 commented on server/clip_server/executors/clip_hg.py
> +                self._encode_images(batch)
Please also apply the optimization tricks introduced in other backends.

2022-06-01 04:49 UTC, numb3r3 commented on server/clip_server/executors/clip_hg.py
> +
separate `preprocess` and `encode` steps into different sub-functions so as to get better monitoring, refer to this https://github.com/jina-ai/clip-as-service/pull/738

2022-06-05 09:05 UTC, hanxiao requested changes
what's the point of this PR? is it just for practicing how to implement executor?

2022-06-07 03:16 UTC, numb3r3 commented
@hanxiao This PR is mainly developed for the community. If the users who already use (or finetune) the clip model from huggingface, then this PR can enable them to easily enjoy the power of jina.

2022-06-07 10:04 UTC, numb3r3 requested changes

2022-06-07 10:04 UTC, numb3r3 commented on server/setup.py
> +        'hg': ['transformers>=4.16.2'],
use `huggingface` instead of `hg`

2022-06-07 10:04 UTC, numb3r3 commented on server/setup.py
> +        'hg': ['transformers>=4.16.2'],
And the commit message should not be `chore:`

2022-06-07 10:29 UTC, numb3r3 requested changes

2022-06-07 10:29 UTC, numb3r3 commented on server/clip_server/executors/clip_hg.py
> +from copy import deepcopy
remove this import if the `copy` is deleted

2022-06-07 10:29 UTC, numb3r3 commented on server/clip_server/executors/clip_hg.py
> +from copy import deepcopy
and clean the unused imports

2022-06-09 01:40 UTC, merged