Draft demo
jina-ai/clip-as-service pull request #778
Opened 2022-07-22 08:20 UTC by jemmyshin

2022-07-22 09:39 UTC, numb3r3 requested changes

2022-07-22 09:39 UTC, numb3r3 commented on client/clip_client/client.py
> +        self._batch_size = 128
please remove the unused codes

2022-07-22 09:39 UTC, numb3r3 commented on client/clip_client/client.py
> +        parameters = kwargs.get('parameters', {})
I prefer to use `kwargs.pop()` instead

2022-07-22 09:39 UTC, numb3r3 commented on client/clip_client/client.py
> +
The `update` is not needed any more. You can directly pass the parameters `on=...` and `inputs` in `post`

2022-07-22 09:39 UTC, numb3r3 commented on client/clip_client/client.py
> +        payload.update(on='/index')
same

2022-07-22 10:37 UTC, numb3r3 requested changes

2022-07-22 10:37 UTC, numb3r3 commented on client/clip_client/client.py
>              )
```suggestion
            self._client.post(
                on=f'/encode/{model_name}'.rstrip('/'),
                inputs=self._iter_doc(content),
                on_done=partial(self._gather_result, results=results),
                **payload,
            )
```

2022-07-22 10:37 UTC, numb3r3 commented on client/clip_client/client.py
> +                on=f'/rank/{model_name}'.rstrip('/'),
same

2022-07-22 10:38 UTC, numb3r3 commented
@jemmyshin Pleas rebase your PR to fix the conflict.

2022-07-25 02:21 UTC, numb3r3 requested changes
We should take care of the user experience. Let's polish the client API to offer an easy-to-use client regarding to user's perspective.

2022-07-25 02:21 UTC, numb3r3 commented on client/clip_client/client.py
> +        payload = self._get_post_parameters(content, kwargs)
rename it as `params`?

2022-07-25 02:21 UTC, numb3r3 commented on client/clip_client/client.py
> +        Given the document with embeddings, this function create an indexer which index
The docstr is not corrct. `index` and `query` functions both accept raw text/image docs without embeddings.

2022-07-25 02:21 UTC, numb3r3 commented on client/clip_client/client.py
> +        Given the document with embeddings, this function create an indexer which index
What's more, we also implment async version, `aindex`, `aquery`

2022-07-25 02:21 UTC, numb3r3 commented on client/clip_client/client.py
> +        Given the document with embeddings, this function create an indexer which index
The `index` should have the same function signature as `encode`

2022-07-25 02:21 UTC, numb3r3 commented on client/clip_client/client.py
> +    def search(self, content: List[str], **kwargs) -> DocumentArray:
`search` should also accept either `str` and `Document`

2022-07-25 04:36 UTC, numb3r3 requested changes

2022-07-25 04:36 UTC, numb3r3 commented on client/clip_client/client.py
> +        parameters = kwargs.pop('parameters', {})
alright, `pop` operator would raise an exception when the given `key` does not exist.

2022-07-26 02:14 UTC, numb3r3 requested changes

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +        parameters: Optional[dict] = {},
same

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +    def encode(self, content, parameters, **kwargs):
it should be optional

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +            not kwargs.pop('show_progress', False),
`pop` would raise an exception if not existing. Hence, we should use get here.

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +                **params,
It seems the `parameters` and `params` is very confusing.

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +                **params,
should we use `post_args` instead of `params`?

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +        parameters: Optional[dict] = {},
change the function signature

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +            not kwargs.pop('show_progress', False),
double-check whether `pop` will work as we expected

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +        ``Document``, will use the ``text`` field as query.
No, `Document` can also be an image doc. The docstr is misleading

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +            - include_metadata: bool, whether return the document metadata in response. Default is True.
the repeated item.

2022-07-26 02:14 UTC, numb3r3 commented on client/clip_client/client.py
> +        If the input is a string, will use this string as query. If the input is a
same

2022-07-26 03:25 UTC, numb3r3 requested changes

2022-07-26 03:25 UTC, numb3r3 commented on client/clip_client/client.py
> +        model_name = parameters.get('model', '')
raise error when `parameters=None`

2022-07-26 03:53 UTC, numb3r3 commented
@jemmyshin please rebase your PR to fix conflicts

2022-07-26 04:24 UTC, numb3r3 requested changes

2022-07-26 04:24 UTC, numb3r3 commented on client/clip_client/client.py
> +        model_name = parameters.get('model', '')
`parameters` can be None, and will raise error here. Please fix it

2022-07-27 03:12 UTC, numb3r3 requested changes

2022-07-27 03:12 UTC, numb3r3 commented on server/clip_server/demo-flow.yml
> +        data_path: /Users/jemfu/Desktop/laion400m/workspace
don't use absolute real path

2022-07-28 02:59 UTC, ZiniuYu commented on client/clip_client/client.py
> +                on='/index',
will we also support selection from multiple indexers?

2022-09-09 05:39 UTC, numb3r3 commented
@jemmyshin This PR has been merged to https://github.com/jina-ai/clip-as-service/pull/816. I will close this PR first. let's work on the new PR.

2022-09-09 05:39 UTC, closed without merging