docs: add model support
jina-ai/clip-as-service pull request #784
Opened 2022-07-26 04:17 UTC by shan-mx

2022-07-26 06:04 UTC, ZiniuYu commented
onnx models are all uploaded to s3

2022-07-26 07:18 UTC, numb3r3 commented
According to this PR, I feel the model table contains some redundant information. Let's first hold this PR until we have an idea how to proceed.

2022-08-02 09:38 UTC, ZiniuYu requested changes

2022-08-02 09:38 UTC, ZiniuYu commented on docs/user-guides/server.md
```suggestion
(model-support)=
```

2022-08-02 09:38 UTC, ZiniuYu commented on docs/user-guides/server.md
> +| `name`                  | Model weights, default is `ViT-B-32::openai`. Full list of models and weights can be found at [here](#model-support)                        |
```suggestion
| `name`                  | Model weights, default is `ViT-B-32::openai`. A full list of models and weights can be found {ref}`here<model-support>`                        |
```

2022-08-02 10:06 UTC, ZiniuYu approved these changes

2022-08-02 10:08 UTC, numb3r3 approved these changes

2022-08-02 10:15 UTC, merged