feat: support not yet supported onnx models
jina-ai/clip-as-service pull request #828
Opened 2022-09-22 15:27 UTC by ZiniuYu

2022-09-23 07:31 UTC, numb3r3 requested changes

2022-09-23 07:31 UTC, numb3r3 commented on server/clip_server/model/clip_onnx.py
>          self._visual_session.disable_fallback()
I belive this block can be wrapped as a helper function.

2022-09-23 10:03 UTC, jemmyshin commented on server/clip_server/executors/clip_onnx.py
> +        name: str = 'M-CLIP/XLM-Roberta-Large-Vit-B-32',
why this changed?

2022-09-23 10:16 UTC, ZiniuYu commented on server/clip_server/executors/clip_onnx.py
> +        name: str = 'M-CLIP/XLM-Roberta-Large-Vit-B-32',
good catch 😅

2022-09-23 10:47 UTC, numb3r3 requested changes

2022-09-23 10:47 UTC, numb3r3 commented on server/clip_server/model/clip_onnx.py
> +        def load_zip_model(model_path, model_type):
```suggestion
        def _load_session_from_zip(model_path: PathLike, model_name: str):
```

2022-09-26 02:52 UTC, numb3r3 approved these changes

2022-09-26 02:52 UTC, merged