fix: check if results are empty
jina-ai/clip-as-service pull request #881
Opened 2022-12-22 14:31 UTC by alaeddine-13

Fixing encoding of a dataset using cas.
To reproduce:
download this file https://jinaai.slack.com/files/U026WRMRL6A/F04GE6JKX0U/dataset.csv

then:
```
from docarray import DocumentArray, Document
with open('dataset.csv') as fp:
  da = DocumentArray.from_csv(fp)

from clip_client import Client

c = Client(
    'grpcs://api.clip.jina.ai:2096', credential={'Authorization': 'atuh-token'}
)

encoded_da = c.encode(da, show_progress=True)
```

2022-12-22 14:33 UTC, alaeddine-13 commented
now a server side issue happens:
```
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "HTTP Balancer service in fail-fast |Gateway: Communication error with deployment clip_t at address(es) {'clip-t.grpc-flow.svc:8080'}. Head or worker(s) may be down."
	debug_error_string = "{"created":"@1671719158.543427000","description":"Error received from peer ipv4:52.58.81.82:2096","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"HTTP Balancer service in fail-fast |Gateway: Communication error with deployment clip_t at address(es) {'clip-t.grpc-flow.svc:8080'}. Head or worker(s) may be down.","grpc_status":14}"
```

2022-12-22 14:43 UTC, ZiniuYu commented on client/clip_client/client.py
> +        if attribute and len(r) > 0:
Ideally `len(r)>0` must hold

2022-12-23 02:52 UTC, jemmyshin requested changes

2022-12-23 02:52 UTC, jemmyshin commented on client/clip_client/client.py
> +        if attribute and len(r) > 0:
why remove this line?

2023-03-02 08:17 UTC, ZiniuYu commented
closing it since it's a connection issue

2023-03-02 08:17 UTC, closed without merging